version: '3.8'

services:
  write:
    image: arm64v8/postgres:14
    container_name: write-Db
    ports:
      - "5432:5432"
    volumes:
      - write-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks: 
      - ledger-network

  read:
    image: arm64v8/postgres:14
    container_name: read-Db
    ports:
      - "5433:5432"
    volumes:
      - read-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks: 
      - ledger-network

  rabbitmq:
    container_name: rabbitmq
    image: arm64v8/rabbitmq:3.10.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq/mnesia
    networks:
      - ledger-network

volumes:
  write-volume:
  read-volume:
  rabbitmq-volume:

networks:
  ledger-network:
    driver: bridge