BEGIN;

CREATE OR REPLACE FUNCTION update_modified_at_func()
	RETURNS TRIGGER AS $$
BEGIN
	NEW.modified_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TABLE IF EXISTS public.account_detail;
CREATE TABLE IF NOT EXISTS public.account_detail(
	id INT8 PRIMARY KEY,
	entity_id INT8 NOT NULL,
	state VARCHAR(32) NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	modified_at TIMESTAMP DEFAULT now()
);

CREATE TRIGGER account_detail_update_modified_at BEFORE UPDATE ON public.account_detail FOR EACH ROW EXECUTE PROCEDURE update_modified_at_func();
CREATE INDEX idx_entity ON public.account_detail (entity_id);

DROP TABLE IF EXISTS public.wallet_detail;
CREATE TABLE IF NOT EXISTS public.wallet_detail(
    id INT8 PRIMARY KEY,
    account_id INT8 NOT NULL,
    asset_type VARCHAR(32) NOT NULL,
    asset_code VARCHAR(32) NOT NULL,
    asset_name VARCHAR(32) NOT NULL,
    balance DECIMAL(21,4) NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    modified_at TIMESTAMP DEFAULT now()
);

CREATE TRIGGER wallet_detail_update_modified_at BEFORE UPDATE ON public.wallet_detail FOR EACH ROW EXECUTE PROCEDURE update_modified_at_func();
CREATE INDEX idx_account ON public.wallet_detail (account_id);

DROP TABLE IF EXISTS public.balance_history_fiat;
CREATE TABLE IF NOT EXISTS public.balance_history_fiat(
	id INT8 GENERATED BY DEFAULT AS IDENTITY,
	entity_id INT8 NOT NULL,
	account_id INT8 NOT NULL,
	wallet_id INT8 NOT NULL,
	asset_code VARCHAR(32) NOT NULL,
    asset_name VARCHAR(32) NOT NULL,
	source_wallet_id INT8 NOT NULL,
	target_wallet_id INT8 NOT NULL,
	amount DECIMAL(21,4) NOT NULL,
	balance DECIMAL(21,4) NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	PRIMARY KEY (id, created_at)
) PARTITION BY RANGE(created_at);

CREATE INDEX idx_entity_account_wallet_created_at_fiat ON public.balance_history_fiat (entity_id, account_id, wallet_id, created_at);

CREATE TABLE balance_history_fiat_2023_08 PARTITION OF balance_history_fiat FOR VALUES FROM ('2023-08-01') TO ('2023-09-01');
CREATE TABLE balance_history_fiat_2023_09 PARTITION OF balance_history_fiat FOR VALUES FROM ('2023-09-01') TO ('2023-10-01');
CREATE TABLE balance_history_fiat_2023_10 PARTITION OF balance_history_fiat FOR VALUES FROM ('2023-10-01') TO ('2023-11-01');
CREATE TABLE balance_history_fiat_2023_11 PARTITION OF balance_history_fiat FOR VALUES FROM ('2023-11-01') TO ('2023-12-01');
CREATE TABLE balance_history_fiat_2023_12 PARTITION OF balance_history_fiat FOR VALUES FROM ('2023-12-01') TO ('2024-01-01');
CREATE TABLE balance_history_fiat_2024_01 PARTITION OF balance_history_fiat FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');
CREATE TABLE balance_history_fiat_2024_02 PARTITION OF balance_history_fiat FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');
CREATE TABLE balance_history_fiat_2024_03 PARTITION OF balance_history_fiat FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');

ALTER TABLE balance_history_fiat_2023_08 ADD CONSTRAINT balance_history_fiat_2023_08_check CHECK (created_at >= '2023-08-01' AND created_at < '2023-09-01');
ALTER TABLE balance_history_fiat_2023_09 ADD CONSTRAINT balance_history_fiat_2023_09_check CHECK (created_at >= '2023-09-01' AND created_at < '2023-10-01');
ALTER TABLE balance_history_fiat_2023_10 ADD CONSTRAINT balance_history_fiat_2023_10_check CHECK (created_at >= '2023-10-01' AND created_at < '2023-11-01');
ALTER TABLE balance_history_fiat_2023_11 ADD CONSTRAINT balance_history_fiat_2023_11_check CHECK (created_at >= '2023-11-01' AND created_at < '2023-12-01');
ALTER TABLE balance_history_fiat_2023_12 ADD CONSTRAINT balance_history_fiat_2023_12_check CHECK (created_at >= '2023-12-01' AND created_at < '2024-01-01');
ALTER TABLE balance_history_fiat_2024_01 ADD CONSTRAINT balance_history_fiat_2024_01_check CHECK (created_at >= '2024-01-01' AND created_at < '2024-02-01');
ALTER TABLE balance_history_fiat_2024_02 ADD CONSTRAINT balance_history_fiat_2024_02_check CHECK (created_at >= '2024-02-01' AND created_at < '2024-03-01');
ALTER TABLE balance_history_fiat_2024_03 ADD CONSTRAINT balance_history_fiat_2024_03_check CHECK (created_at >= '2024-03-01' AND created_at < '2024-04-01');


DROP TABLE IF EXISTS public.balance_history_crypto;
CREATE TABLE IF NOT EXISTS public.balance_history_crypto(
	id INT8 GENERATED BY DEFAULT AS IDENTITY,
	entity_id INT8 NOT NULL,
	account_id INT8 NOT NULL,
	wallet_id INT8 NOT NULL,
	asset_code VARCHAR(32) NOT NULL,
    asset_name VARCHAR(32) NOT NULL,
	source_wallet_id INT8 NOT NULL,
	target_wallet_id INT8 NOT NULL,
	amount DECIMAL(21,4) NOT NULL,
	balance DECIMAL(21,4) NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	PRIMARY KEY (id, created_at)
) PARTITION BY RANGE(created_at);

CREATE INDEX idx_entity_account_wallet_created_at_crypto ON public.balance_history_crypto (entity_id, account_id, wallet_id, created_at);

CREATE TABLE balance_history_crypto_2023_08 PARTITION OF balance_history_crypto FOR VALUES FROM ('2023-08-01') TO ('2023-09-01');
CREATE TABLE balance_history_crypto_2023_09 PARTITION OF balance_history_crypto FOR VALUES FROM ('2023-09-01') TO ('2023-10-01');
CREATE TABLE balance_history_crypto_2023_10 PARTITION OF balance_history_crypto FOR VALUES FROM ('2023-10-01') TO ('2023-11-01');
CREATE TABLE balance_history_crypto_2023_11 PARTITION OF balance_history_crypto FOR VALUES FROM ('2023-11-01') TO ('2023-12-01');
CREATE TABLE balance_history_crypto_2023_12 PARTITION OF balance_history_crypto FOR VALUES FROM ('2023-12-01') TO ('2024-01-01');
CREATE TABLE balance_history_crypto_2024_01 PARTITION OF balance_history_crypto FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');
CREATE TABLE balance_history_crypto_2024_02 PARTITION OF balance_history_crypto FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');
CREATE TABLE balance_history_crypto_2024_03 PARTITION OF balance_history_crypto FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');

ALTER TABLE balance_history_crypto_2023_08 ADD CONSTRAINT balance_history_crypto_2023_08_check CHECK (created_at >= '2023-08-01' AND created_at < '2023-09-01');
ALTER TABLE balance_history_crypto_2023_09 ADD CONSTRAINT balance_history_crypto_2023_09_check CHECK (created_at >= '2023-09-01' AND created_at < '2023-10-01');
ALTER TABLE balance_history_crypto_2023_10 ADD CONSTRAINT balance_history_crypto_2023_10_check CHECK (created_at >= '2023-10-01' AND created_at < '2023-11-01');
ALTER TABLE balance_history_crypto_2023_11 ADD CONSTRAINT balance_history_crypto_2023_11_check CHECK (created_at >= '2023-11-01' AND created_at < '2023-12-01');
ALTER TABLE balance_history_crypto_2023_12 ADD CONSTRAINT balance_history_crypto_2023_12_check CHECK (created_at >= '2023-12-01' AND created_at < '2024-01-01');
ALTER TABLE balance_history_crypto_2024_01 ADD CONSTRAINT balance_history_crypto_2024_01_check CHECK (created_at >= '2024-01-01' AND created_at < '2024-02-01');
ALTER TABLE balance_history_crypto_2024_02 ADD CONSTRAINT balance_history_crypto_2024_02_check CHECK (created_at >= '2024-02-01' AND created_at < '2024-03-01');
ALTER TABLE balance_history_crypto_2024_03 ADD CONSTRAINT balance_history_crypto_2024_03_check CHECK (created_at >= '2024-03-01' AND created_at < '2024-04-01');

DROP TABLE IF EXISTS public.balance_history_stock;
CREATE TABLE IF NOT EXISTS public.balance_history_stock(
	id INT8 GENERATED BY DEFAULT AS IDENTITY,
	entity_id INT8 NOT NULL,
	account_id INT8 NOT NULL,
	wallet_id INT8 NOT NULL,
	asset_code VARCHAR(32) NOT NULL,
    asset_name VARCHAR(32) NOT NULL,
	source_wallet_id INT8 NOT NULL,
	target_wallet_id INT8 NOT NULL,
	amount DECIMAL(21,4) NOT NULL,
	balance DECIMAL(21,4) NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	PRIMARY KEY (id, created_at)
) PARTITION BY RANGE(created_at);

CREATE INDEX idx_entity_account_wallet_created_at_stock ON public.balance_history_stock (entity_id, account_id, wallet_id, created_at);

CREATE TABLE balance_history_stock_2023_08 PARTITION OF balance_history_stock FOR VALUES FROM ('2023-08-01') TO ('2023-09-01');
CREATE TABLE balance_history_stock_2023_09 PARTITION OF balance_history_stock FOR VALUES FROM ('2023-09-01') TO ('2023-10-01');
CREATE TABLE balance_history_stock_2023_10 PARTITION OF balance_history_stock FOR VALUES FROM ('2023-10-01') TO ('2023-11-01');
CREATE TABLE balance_history_stock_2023_11 PARTITION OF balance_history_stock FOR VALUES FROM ('2023-11-01') TO ('2023-12-01');
CREATE TABLE balance_history_stock_2023_12 PARTITION OF balance_history_stock FOR VALUES FROM ('2023-12-01') TO ('2024-01-01');
CREATE TABLE balance_history_stock_2024_01 PARTITION OF balance_history_stock FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');
CREATE TABLE balance_history_stock_2024_02 PARTITION OF balance_history_stock FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');
CREATE TABLE balance_history_stock_2024_03 PARTITION OF balance_history_stock FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');

ALTER TABLE balance_history_stock_2023_08 ADD CONSTRAINT balance_history_stock_2023_08_check CHECK (created_at >= '2023-08-01' AND created_at < '2023-09-01');
ALTER TABLE balance_history_stock_2023_09 ADD CONSTRAINT balance_history_stock_2023_09_check CHECK (created_at >= '2023-09-01' AND created_at < '2023-10-01');
ALTER TABLE balance_history_stock_2023_10 ADD CONSTRAINT balance_history_stock_2023_10_check CHECK (created_at >= '2023-10-01' AND created_at < '2023-11-01');
ALTER TABLE balance_history_stock_2023_11 ADD CONSTRAINT balance_history_stock_2023_11_check CHECK (created_at >= '2023-11-01' AND created_at < '2023-12-01');
ALTER TABLE balance_history_stock_2023_12 ADD CONSTRAINT balance_history_stock_2023_12_check CHECK (created_at >= '2023-12-01' AND created_at < '2024-01-01');
ALTER TABLE balance_history_stock_2024_01 ADD CONSTRAINT balance_history_stock_2024_01_check CHECK (created_at >= '2024-01-01' AND created_at < '2024-02-01');
ALTER TABLE balance_history_stock_2024_02 ADD CONSTRAINT balance_history_stock_2024_02_check CHECK (created_at >= '2024-02-01' AND created_at < '2024-03-01');
ALTER TABLE balance_history_stock_2024_03 ADD CONSTRAINT balance_history_stock_2024_03_check CHECK (created_at >= '2024-03-01' AND created_at < '2024-04-01');

DROP TABLE IF EXISTS public.balance_history_bond;
CREATE TABLE IF NOT EXISTS public.balance_history_bond(
	id INT8 GENERATED BY DEFAULT AS IDENTITY,
	entity_id INT8 NOT NULL,
	account_id INT8 NOT NULL,
	wallet_id INT8 NOT NULL,
	asset_code VARCHAR(32) NOT NULL,
    asset_name VARCHAR(32) NOT NULL,
	source_wallet_id INT8 NOT NULL,
	target_wallet_id INT8 NOT NULL,
	amount DECIMAL(21,4) NOT NULL,
	balance DECIMAL(21,4) NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE INDEX idx_entity_account_wallet_created_at_bond ON public.balance_history_bond (entity_id, account_id, wallet_id, created_at);

CREATE TABLE balance_history_bond_2023_08 PARTITION OF balance_history_bond FOR VALUES FROM ('2023-08-01') TO ('2023-09-01');
CREATE TABLE balance_history_bond_2023_09 PARTITION OF balance_history_bond FOR VALUES FROM ('2023-09-01') TO ('2023-10-01');
CREATE TABLE balance_history_bond_2023_10 PARTITION OF balance_history_bond FOR VALUES FROM ('2023-10-01') TO ('2023-11-01');
CREATE TABLE balance_history_bond_2023_11 PARTITION OF balance_history_bond FOR VALUES FROM ('2023-11-01') TO ('2023-12-01');
CREATE TABLE balance_history_bond_2023_12 PARTITION OF balance_history_bond FOR VALUES FROM ('2023-12-01') TO ('2024-01-01');
CREATE TABLE balance_history_bond_2024_01 PARTITION OF balance_history_bond FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');
CREATE TABLE balance_history_bond_2024_02 PARTITION OF balance_history_bond FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');
CREATE TABLE balance_history_bond_2024_03 PARTITION OF balance_history_bond FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');

ALTER TABLE balance_history_bond_2023_08 ADD CONSTRAINT balance_history_bond_2023_08_check CHECK (created_at >= '2023-08-01' AND created_at < '2023-09-01');
ALTER TABLE balance_history_bond_2023_09 ADD CONSTRAINT balance_history_bond_2023_09_check CHECK (created_at >= '2023-09-01' AND created_at < '2023-10-01');
ALTER TABLE balance_history_bond_2023_10 ADD CONSTRAINT balance_history_bond_2023_10_check CHECK (created_at >= '2023-10-01' AND created_at < '2023-11-01');
ALTER TABLE balance_history_bond_2023_11 ADD CONSTRAINT balance_history_bond_2023_11_check CHECK (created_at >= '2023-11-01' AND created_at < '2023-12-01');
ALTER TABLE balance_history_bond_2023_12 ADD CONSTRAINT balance_history_bond_2023_12_check CHECK (created_at >= '2023-12-01' AND created_at < '2024-01-01');
ALTER TABLE balance_history_bond_2024_01 ADD CONSTRAINT balance_history_bond_2024_01_check CHECK (created_at >= '2024-01-01' AND created_at < '2024-02-01');
ALTER TABLE balance_history_bond_2024_02 ADD CONSTRAINT balance_history_bond_2024_02_check CHECK (created_at >= '2024-02-01' AND created_at < '2024-03-01');
ALTER TABLE balance_history_bond_2024_03 ADD CONSTRAINT balance_history_bond_2024_03_check CHECK (created_at >= '2024-03-01' AND created_at < '2024-04-01');