INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (1, 1, 'FIAT', 'CNY','CNY', 1000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (2, 1, 'FIAT', 'USD','USD', 900);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (3, 1, 'FIAT', 'EUR','EUR', 800);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (4, 1, 'CRYPTO', 'BTC','Bitcoin', 10000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (5, 1, 'CRYPTO', 'ETH','Ethereum', 9000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (6, 1, 'CRYPTO', 'XRP','Ripple', 8000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (7, 1, 'STOCK', 'AAPL','Apple Inc', 100000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (8, 1, 'STOCK', 'AMZN','Amazon.com Inc', 90000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (9, 1, 'STOCK', 'MSFT','Microsoft Corporation', 80000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (10, 1, 'BOND', 'GB3:GOV','US BOND 3 Month', 1000000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (11, 1, 'BOND', 'GB6:GOV','US BOND 6 Month', 900000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (12, 1, 'BOND', 'GB12:GOV','US BOND 12 Month', 800000);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (13, 4, 'CRYPTO', 'XRP','Ripple', 6666);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (14, 4, 'CRYPTO', 'LTC','Litecoin', 7777);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (15, 5, 'STOCK', 'MSFT','Microsoft Corporation', 8888);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (16, 5, 'STOCK', 'GOOGL','Alphabet Inc.', 9999);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (17, 6, 'STOCK', 'MSFT','Microsoft Corporation', 12345);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (18, 6, 'STOCK', 'GOOGL','Alphabet Inc.', 67890);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (19, 7, 'FIAT', 'CNY','CNY', 100);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (20, 7, 'FIAT', 'USD','USD', 90);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (21, 7, 'CRYPTO', 'BTC', 'BitCoin',80);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (22, 7, 'CRYPTO', 'ETH','Ethereum', 70);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (23, 8, 'STOCK', 'AAPL','Apple Inc.', 60);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (24, 8, 'STOCK', 'GOOGL','Alphabet Inc.', 60);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (25, 8, 'BOND', 'GB3:GOV','US BOND 3 Month', 0);
INSERT INTO wallet_detail (id, account_id, asset_type, asset_code, asset_name, balance) VALUES (26, 8, 'BOND', 'GB6:GOV','US BOND 6 Month', 0);
