BEGIN;

CREATE OR REPLACE FUNCTION update_modified_at_func()
	RETURNS TRIGGER AS $$
BEGIN
	NEW.modified_at = now();
RETURN NEW;
END;
$$ language 'plpgsql';

DROP TABLE IF EXISTS public.entity;
CREATE TABLE IF NOT EXISTS public.entity(
	id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(128),
	created_at TIMESTAMP DEFAULT now(),
	modified_at TIMESTAMP DEFAULT now()
);
CREATE TRIGGER entity_update_modified_at BEFORE UPDATE ON public.entity FOR EACH ROW EXECUTE PROCEDURE update_modified_at_func();

DROP TABLE IF EXISTS public.account;
CREATE TABLE IF NOT EXISTS public.account(
	id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	entity_id INT8 NOT NULL,
	state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
	created_at TIMESTAMP DEFAULT now(),
	modified_at TIMESTAMP DEFAULT now()
);
CREATE TRIGGER account_update_modified_at BEFORE UPDATE ON public.account FOR EACH ROW EXECUTE PROCEDURE update_modified_at_func();

DROP TABLE IF EXISTS public.asset;
CREATE TABLE IF NOT EXISTS public.asset(
	id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	type VARCHAR(32) NOT NULL,
	code VARCHAR(32) NOT NULL,
	name VARCHAR(128) NOT NULL,
	status VARCHAR(16) DEFAULT 'AVAILABLE',
	created_at TIMESTAMP DEFAULT now(),
	modified_at TIMESTAMP DEFAULT now()
);
CREATE TRIGGER asset_update_modified_at BEFORE UPDATE ON public.asset FOR EACH ROW EXECUTE PROCEDURE update_modified_at_func();
CREATE UNIQUE INDEX idx_unique_type_code ON public.asset (type, code);

DROP TABLE IF EXISTS public.wallet;
CREATE TABLE IF NOT EXISTS public.wallet(
	id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id INT8 NOT NULL,
	asset_id INT8 NOT NULL,
	balance DECIMAL(21,4) DEFAULT 0,
	freeze_balance DECIMAL(21,4) DEFAULT 0,
	created_at TIMESTAMP DEFAULT now(),
	modified_at TIMESTAMP DEFAULT now()
);
CREATE TRIGGER wallet_update_modified_at BEFORE UPDATE ON public.wallet FOR EACH ROW EXECUTE PROCEDURE update_modified_at_func();


DROP TABLE IF EXISTS public.movement;
CREATE TABLE IF NOT EXISTS public.movement(
	id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	entity_id INT8 NOT NULL,
	source_account_id INT8 NOT NULL,
	target_account_id INT8 NOT NULL,
	source_wallet_id INT8 NOT NULL,
	target_wallet_id INT8 NOT NULL,
	amount DECIMAL(21,4) NOT NULL,
	state VARCHAR(32) NOT NULL,
	remark VARCHAR(32),
	created_at TIMESTAMP DEFAULT now(),
	modified_at TIMESTAMP DEFAULT now()
);