DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
DATASOURCE_USERNAME: postgres
DATASOURCE_PASSWORD: postgres

PS_URL: jdbc:postgresql://localhost:5432/postgres
FLYWAY_USERNAME: postgres
FLYWAY_PASSWORD: postgres